apiVersion: v1
kind: Service
metadata:
  name: sidecar-containers-service
spec:
  selector:
    app: sidecar-containers
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
